
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author 84978
 */
public class AddNewCustomer extends javax.swing.JPanel {

    /**
     * Creates new form AddNewCustomer
     */
    public AddNewCustomer() {
        initComponents();
        String MaKH = new Helper().generateUniqueCustomerId();
        maKHTxt.setText(MaKH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maKHTxt = new javax.swing.JTextField();
        Họ = new javax.swing.JLabel();
        HoTxt = new javax.swing.JTextField();
        TeN = new javax.swing.JLabel();
        TenTxt = new javax.swing.JTextField();
        ngaySinh = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        duongTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phuongTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        quanTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tpTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        soNhaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sdtTxt = new javax.swing.JTextField();
        NgayCBox = new javax.swing.JComboBox<>();
        ThangCBox = new javax.swing.JComboBox<>();
        NamCBox = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(31, 34, 46));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã khách hàng");

        maKHTxt.setEditable(false);
        maKHTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Họ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Họ.setForeground(new java.awt.Color(255, 255, 255));
        Họ.setText("Họ");

        HoTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HoTxtKeyTyped(evt);
            }
        });

        TeN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TeN.setForeground(new java.awt.Color(255, 255, 255));
        TeN.setText("Tên");

        TenTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TenTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TenTxtKeyTyped(evt);
            }
        });

        ngaySinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ngaySinh.setForeground(new java.awt.Color(255, 255, 255));
        ngaySinh.setText("Ngày Sinh");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Đường");

        duongTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        duongTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                duongTxtKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phường");

        phuongTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phuongTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phuongTxtKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quận");

        quanTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quanTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quanTxtKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thành Phố");

        tpTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tpTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpTxtKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số Nhà");

        soNhaTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soNhaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soNhaTxtKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Số ĐT");

        sdtTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sdtTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sdtTxtKeyTyped(evt);
            }
        });

        NgayCBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NgayCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        ThangCBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ThangCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        ThangCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThangCBoxActionPerformed(evt);
            }
        });

        NamCBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2021" }));
        NamCBox.setSelectedIndex(50);
        NamCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Họ)
                            .addComponent(jLabel1)
                            .addComponent(TeN)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngaySinh)
                            .addComponent(jLabel5))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HoTxt)
                    .addComponent(TenTxt)
                    .addComponent(soNhaTxt)
                    .addComponent(maKHTxt)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(NgayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ThangCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phuongTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(duongTxt)
                    .addComponent(quanTxt)
                    .addComponent(tpTxt)
                    .addComponent(sdtTxt))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(maKHTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phuongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(HoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Họ))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeN))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ngaySinh)
                    .addComponent(NgayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThangCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(soNhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HoTxtKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()))&&!(Character.isSpaceChar(evt.getKeyChar()))){
                evt.consume();
            }
        int len = HoTxt.getText().length();
        if(len == 30){
           evt.consume(); 
        }
    }//GEN-LAST:event_HoTxtKeyTyped

    private void TenTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TenTxtKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()))&&!(Character.isSpaceChar(evt.getKeyChar()))){
                evt.consume();
            }
        int len = TenTxt.getText().length();
        if(len == 30){
           evt.consume(); 
        }
    }//GEN-LAST:event_TenTxtKeyTyped

    private void soNhaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soNhaTxtKeyTyped
        int len = soNhaTxt.getText().length();
        if(len == 5){
           evt.consume(); // Chỉ cho nhập 5 kí tự
        }
    }//GEN-LAST:event_soNhaTxtKeyTyped

    private void duongTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duongTxtKeyTyped
        int len = duongTxt.getText().length();
        if(len == 30){
           evt.consume(); 
        }
    }//GEN-LAST:event_duongTxtKeyTyped

    private void phuongTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phuongTxtKeyTyped
        int len = phuongTxt.getText().length();
        if(len == 20){
           evt.consume(); 
        }
    }//GEN-LAST:event_phuongTxtKeyTyped

    private void quanTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quanTxtKeyTyped
        int len = quanTxt.getText().length();
        if(len == 20){
           evt.consume(); 
        }
    }//GEN-LAST:event_quanTxtKeyTyped

    private void tpTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpTxtKeyTyped
        int len = tpTxt.getText().length();
        if(len == 20){
           evt.consume(); 
        }
    }//GEN-LAST:event_tpTxtKeyTyped

    private void sdtTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdtTxtKeyTyped
        if(!(Character.isDigit(evt.getKeyChar()))){
                evt.consume();
            }
        int len = sdtTxt.getText().length();
        if(len == 10){
           evt.consume(); 
        }
    }//GEN-LAST:event_sdtTxtKeyTyped

    private void ThangCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThangCBoxActionPerformed
        String Nam = NamCBox.getSelectedItem().toString();
        int nam = Integer.parseInt(Nam);
        int thang = Integer.parseInt(ThangCBox.getSelectedItem().toString());
        int ngay=0;
        Boolean Nhuan = false;
        if(nam%400==0||(nam%100!=0||nam%4==0)){
            Nhuan = true;
        }
        switch (thang){
            case 1: case 3: case 5: case 7: case 8: case 10: case 12:{
                ngay =31;
                break;
                
            }
            case 4: case 6: case 9: case 11:{
                ngay =30;
                break;
            }
            case 2:{
                if(Nhuan){
                    ngay =29;
                }
                else ngay =28;
            }
             
        }
        Vector<String> Ngay = new Vector();
        for(int i=1;i<=ngay;i++){
                    Ngay.add(Integer.toString(i));
                }
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(Ngay);
        NgayCBox.setModel(dcbm);
    }//GEN-LAST:event_ThangCBoxActionPerformed

    private void NamCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamCBoxActionPerformed
        String Nam = NamCBox.getSelectedItem().toString();
        int nam = Integer.parseInt(Nam);
        int thang = Integer.parseInt(ThangCBox.getSelectedItem().toString());
        int ngay=0;
        Boolean Nhuan = false;
        if(nam%400==0||(nam%100!=0&&nam%4==0)){
            Nhuan = true;
        }
        switch (thang){
            case 1: case 3: case 5: case 7: case 8: case 10: case 12:{
                ngay =31;
                break;
                
            }
            case 4: case 6: case 9: case 11:{
                ngay =30;
                break;
            }
            case 2:{
                if(Nhuan){
                    ngay =29;
                    break;
                }
                else ngay =28;
            }
             
        }
        Vector<String> Ngay = new Vector();
        for(int i=1;i<=ngay;i++){
                    Ngay.add(Integer.toString(i));
                }
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(Ngay);
        NgayCBox.setModel(dcbm);
    }//GEN-LAST:event_NamCBoxActionPerformed
    public Boolean addNewCustomer(){
        
        String MaKH = maKHTxt.getText();
        String ho = HoTxt.getText();
        if(ho.equals("")){
            
            JOptionPane.showMessageDialog(null, "Nhập họ");
            return false;
        }
        String ten=TenTxt.getText();
        if(ten.equals("")){
            
            JOptionPane.showMessageDialog(null, "Nhập tên");
            return false;
        }
        String ngay =NgayCBox.getSelectedItem().toString();
        if(ngay.length()==1){
            ngay='0'+ngay;
        }
        String thang =ThangCBox.getSelectedItem().toString();
        if(thang.length()==1){
            thang='0'+thang;
        }
        String nam = NamCBox.getSelectedItem().toString();
        String Dob = nam+thang+ngay;
        
        String soNha = soNhaTxt.getText();
        if(soNha.equals("")){
            
            JOptionPane.showMessageDialog(null, "Nhập số nhà");
            return false;
        }
        String duong = duongTxt.getText();
        if(duong.equals("")){
            
            JOptionPane.showMessageDialog(null, "Nhập đường");
            return false;
        }
        String phuong = phuongTxt.getText();
        if(phuong.equals("")){
            
            JOptionPane.showMessageDialog(null, "Nhập phường");
            return false;
        }
        String quan =quanTxt.getText();
        if(quan.equals("")){
            
            JOptionPane.showMessageDialog(null, "Nhập quận");
            return false;
        }
        String tp = tpTxt.getText();
        if(tp.equals("")){
            
            JOptionPane.showMessageDialog(null, "Nhập thành phố");
            return false;
        }
        String sdt = sdtTxt.getText();
        if(sdt.equals("")){
            
            JOptionPane.showMessageDialog(null, "Nhập số điện thoại");
            return false;
        }
        if(new DBUpdater().AddNewCustomer(MaKH, ho, ten, Dob, soNha, duong, phuong, quan, tp, sdt)){
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            return true;
        }
        else{
            JOptionPane.showMessageDialog(null, "Lỗi");
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HoTxt;
    private javax.swing.JLabel Họ;
    private javax.swing.JComboBox<String> NamCBox;
    private javax.swing.JComboBox<String> NgayCBox;
    private javax.swing.JLabel TeN;
    private javax.swing.JTextField TenTxt;
    private javax.swing.JComboBox<String> ThangCBox;
    private javax.swing.JTextField duongTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maKHTxt;
    private javax.swing.JLabel ngaySinh;
    private javax.swing.JTextField phuongTxt;
    private javax.swing.JTextField quanTxt;
    private javax.swing.JTextField sdtTxt;
    private javax.swing.JTextField soNhaTxt;
    private javax.swing.JTextField tpTxt;
    // End of variables declaration//GEN-END:variables
}
